//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Memory_Game
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jouer
    {
        public int idUser { get; set; }
        public int idEtat { get; set; }
        public int idPartie { get; set; }
        public string listeCombine { get; set; }
    
        public virtual Etat Etat { get; set; }
        public virtual Partie Partie { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
