//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Memory_Game
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MemoryContextContainer1 : DbContext
    {
        public MemoryContextContainer1()
            : base("name=MemoryContextContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Etat> Etats { get; set; }
        public virtual DbSet<Jouer> Jouers { get; set; }
        public virtual DbSet<Partie> Parties { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
    }
}
